-- =====================================================================
-- 범정부 응용프로그램 운영관리시스템 (eGov-Ops) 스키마
-- 전자정부 표준프레임워크 / 응용프로그램 표준운영절차 데이터 모델
-- =====================================================================

DROP TABLE IF EXISTS OPS_CHECK_ITEM;
DROP TABLE IF EXISTS OPS_CHECK;
DROP TABLE IF EXISTS OPS_RELEASE;
DROP TABLE IF EXISTS OPS_CHANGE;
DROP TABLE IF EXISTS OPS_INCIDENT_HIS;
DROP TABLE IF EXISTS OPS_INCIDENT;
DROP TABLE IF EXISTS OPS_CODE;
DROP TABLE IF EXISTS OPS_SYSTEM;
DROP TABLE IF EXISTS OPS_USER;

-- 사용자(운영자) ---------------------------------------------------------
CREATE TABLE OPS_USER (
    USER_ID    VARCHAR(20)   NOT NULL,
    USER_NM    VARCHAR(50)   NOT NULL,
    PASSWORD   VARCHAR(100)  NOT NULL,
    ROLE       VARCHAR(20)   NOT NULL,  -- ADMIN / OPERATOR / USER
    DEPT_NM    VARCHAR(100),
    EMAIL      VARCHAR(100),
    TELNO      VARCHAR(20),
    USE_AT     CHAR(1)       DEFAULT 'Y',
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_USER PRIMARY KEY (USER_ID)
);

-- 응용시스템(운영대상) 마스터 -------------------------------------------
CREATE TABLE OPS_SYSTEM (
    SYS_ID     VARCHAR(20)   NOT NULL,
    SYS_NM     VARCHAR(100)  NOT NULL,
    SYS_DESC   VARCHAR(500),
    MNGR_NM    VARCHAR(50),               -- 운영담당자
    MNGR_DEPT  VARCHAR(100),              -- 운영부서
    GRAD       VARCHAR(20),               -- 중요도등급 (1~3등급)
    USE_AT     CHAR(1)       DEFAULT 'Y',
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_SYSTEM PRIMARY KEY (SYS_ID)
);

-- 공통코드 --------------------------------------------------------------
CREATE TABLE OPS_CODE (
    CODE_GRP   VARCHAR(30)   NOT NULL,    -- 코드그룹 (예: INCIDENT_STATUS)
    CODE_ID    VARCHAR(30)   NOT NULL,    -- 코드값
    CODE_NM    VARCHAR(100)  NOT NULL,    -- 코드명
    SORT_ORDR  INT           DEFAULT 1,
    USE_AT     CHAR(1)       DEFAULT 'Y',
    CONSTRAINT PK_OPS_CODE PRIMARY KEY (CODE_GRP, CODE_ID)
);

-- 장애관리 --------------------------------------------------------------
CREATE TABLE OPS_INCIDENT (
    INC_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    TITLE      VARCHAR(200)  NOT NULL,
    CONTENT    VARCHAR(2000),
    SEVERITY   VARCHAR(10)   NOT NULL,    -- 1~4 등급 (1:긴급)
    STATUS     VARCHAR(20)   NOT NULL,    -- RECEIVED/ANALYZING/ACTING/RESOLVED/CLOSED
    OCCR_DT    TIMESTAMP,                 -- 발생일시
    RCPT_DT    TIMESTAMP,                 -- 접수일시
    RESOLVE_DT TIMESTAMP,                 -- 조치완료일시
    CAUSE      VARCHAR(2000),             -- 장애원인
    ACTION     VARCHAR(2000),             -- 조치내용
    CHARGER_ID VARCHAR(20),               -- 처리담당자
    REG_ID     VARCHAR(20),
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_INCIDENT PRIMARY KEY (INC_ID)
);

-- 장애 처리이력 ---------------------------------------------------------
CREATE TABLE OPS_INCIDENT_HIS (
    HIS_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    INC_ID     BIGINT        NOT NULL,
    STATUS     VARCHAR(20)   NOT NULL,
    CONTENT    VARCHAR(2000),
    PROC_ID    VARCHAR(20),
    PROC_DT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_INCIDENT_HIS PRIMARY KEY (HIS_ID)
);

-- 변경관리 --------------------------------------------------------------
CREATE TABLE OPS_CHANGE (
    CHG_ID       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID       VARCHAR(20)  NOT NULL,
    TITLE        VARCHAR(200) NOT NULL,
    CHG_TYPE     VARCHAR(20)  NOT NULL,   -- PROGRAM/DATABASE/CONFIG/EMERGENCY
    REASON       VARCHAR(2000),           -- 변경사유
    CONTENT      VARCHAR(2000),           -- 변경내용
    STATUS       VARCHAR(20)  NOT NULL,   -- REQUESTED/REVIEWING/APPROVED/REJECTED/APPLIED/COMPLETED
    REQ_ID       VARCHAR(20),             -- 요청자
    REQ_DT       TIMESTAMP,               -- 요청일시
    APPR_ID      VARCHAR(20),             -- 승인자
    APPR_DT      TIMESTAMP,               -- 승인일시
    APPR_OPINION VARCHAR(1000),           -- 심의의견
    PLAN_DT      DATE,                    -- 적용예정일
    APPLY_DT     TIMESTAMP,               -- 실적용일시
    REG_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CHANGE PRIMARY KEY (CHG_ID)
);

-- 배포(릴리즈)관리 ------------------------------------------------------
CREATE TABLE OPS_RELEASE (
    REL_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    CHG_ID     BIGINT,                    -- 연계 변경요청
    VER        VARCHAR(30)   NOT NULL,    -- 버전
    TITLE      VARCHAR(200)  NOT NULL,
    CONTENT    VARCHAR(2000),
    STATUS     VARCHAR(20)   NOT NULL,    -- PLANNED/APPROVED/DEPLOYING/DEPLOYED/ROLLBACK
    PLAN_DT    TIMESTAMP,                 -- 배포예정일시
    DEPLOY_DT  TIMESTAMP,                 -- 배포일시
    CHARGER_ID VARCHAR(20),
    RESULT     VARCHAR(1000),             -- 배포결과
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_RELEASE PRIMARY KEY (REL_ID)
);

-- 운영점검(일일/정기) ---------------------------------------------------
CREATE TABLE OPS_CHECK (
    CHK_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    CHK_TYPE   VARCHAR(20)   NOT NULL,    -- DAILY/WEEKLY/MONTHLY
    CHK_DT     DATE          NOT NULL,    -- 점검일자
    CHKR_ID    VARCHAR(20),               -- 점검자
    RESULT     VARCHAR(20)   NOT NULL,    -- NORMAL/ABNORMAL
    REMARK     VARCHAR(1000),
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CHECK PRIMARY KEY (CHK_ID)
);

-- 운영점검 항목별 결과 --------------------------------------------------
CREATE TABLE OPS_CHECK_ITEM (
    ITEM_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CHK_ID      BIGINT       NOT NULL,
    ITEM_NM     VARCHAR(200) NOT NULL,    -- 점검항목명
    ITEM_RESULT VARCHAR(20)  NOT NULL,    -- NORMAL/ABNORMAL
    ITEM_REMARK VARCHAR(500),
    CONSTRAINT PK_OPS_CHECK_ITEM PRIMARY KEY (ITEM_ID)
);
