-- =====================================================================
-- 범정부 응용프로그램 운영관리시스템 (eGov-Sop) 스키마
-- 전자정부 표준프레임워크 / 응용프로그램 표준운영절차 데이터 모델
-- =====================================================================

DROP TABLE IF EXISTS OPS_CHECK_ITEM;
DROP TABLE IF EXISTS OPS_CHECK;
DROP TABLE IF EXISTS OPS_RELEASE;
DROP TABLE IF EXISTS OPS_CHANGE;
DROP TABLE IF EXISTS OPS_INCIDENT_HIS;
DROP TABLE IF EXISTS OPS_INCIDENT;
DROP TABLE IF EXISTS OPS_CODE;
DROP TABLE IF EXISTS OPS_SYSTEM;
DROP TABLE IF EXISTS OPS_USER;

-- 사용자(운영자) ---------------------------------------------------------
CREATE TABLE OPS_USER (
    USER_ID    VARCHAR(20)   NOT NULL,
    USER_NM    VARCHAR(50)   NOT NULL,
    PASSWORD   VARCHAR(100)  NOT NULL,
    ROLE       VARCHAR(20)   NOT NULL,  -- ADMIN / OPERATOR / USER
    POSITN     VARCHAR(30),             -- 직급 (성명(직급) 표기용)
    DEPT_CD    VARCHAR(20),             -- 소속 부서코드(OPS_DEPT.DEPT_CD) — 표시는 부서명으로 조인
    EMAIL      VARCHAR(100),
    TELNO      VARCHAR(20),
    USE_AT     CHAR(1)       DEFAULT 'Y',
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_USER PRIMARY KEY (USER_ID)
);

-- 응용시스템(운영대상) 마스터 -------------------------------------------
CREATE TABLE OPS_SYSTEM (
    SYS_ID     VARCHAR(20)   NOT NULL,
    SYS_NM     VARCHAR(100)  NOT NULL,
    SYS_DESC   VARCHAR(500),
    MNGR_NM    VARCHAR(50),               -- 운영담당자(성명)
    MNGR_ID    VARCHAR(20),               -- 운영담당자 계정(사용자ID) — 요청 열람·처리 권한
    MNGR_DEPT  VARCHAR(100),              -- 운영부서
    GRAD       VARCHAR(20),               -- 중요도등급 (1~3등급)
    VCS_TYPE      VARCHAR(10) DEFAULT 'GIT', -- 형상관리 유형 (GIT/SVN)
    GIT_URL       VARCHAR(300),           -- 배포 저장소 URL (Git/SVN)
    GIT_BRANCH    VARCHAR(100),           -- 기본 브랜치(Git)/트렁크·경로(SVN)
    DEPLOY_PATH   VARCHAR(300),           -- 배포(체크아웃) 대상 경로
    DEPLOY_SCRIPT VARCHAR(4000),          -- 체크아웃 후 실행 배포 스크립트
    USE_AT     CHAR(1)       DEFAULT 'Y',
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_SYSTEM PRIMARY KEY (SYS_ID)
);

-- 공통코드 --------------------------------------------------------------
CREATE TABLE OPS_CODE (
    CODE_GRP   VARCHAR(30)   NOT NULL,    -- 코드그룹 (예: INCIDENT_STATUS)
    CODE_ID    VARCHAR(30)   NOT NULL,    -- 코드값
    CODE_NM    VARCHAR(100)  NOT NULL,    -- 코드명
    SORT_ORDR  INT           DEFAULT 1,
    USE_AT     CHAR(1)       DEFAULT 'Y',
    UPPER_CODE VARCHAR(30),               -- 상위코드값(계층코드) : 소분류→대분류 매핑 (예 CSR_SUBTYPE→CSR_TYPE)
    CONSTRAINT PK_OPS_CODE PRIMARY KEY (CODE_GRP, CODE_ID)
);

-- 공통코드 그룹 마스터(그룹코드 → 그룹명)
DROP TABLE IF EXISTS OPS_CODE_GRP;
CREATE TABLE OPS_CODE_GRP (
    GRP_CD     VARCHAR(30)   NOT NULL,    -- 코드그룹코드
    GRP_NM     VARCHAR(100)  NOT NULL,    -- 코드그룹명
    SORT_ORDR  INT           DEFAULT 1,
    USE_AT     CHAR(1)       DEFAULT 'Y',
    CONSTRAINT PK_OPS_CODE_GRP PRIMARY KEY (GRP_CD)
);

-- 장애관리 --------------------------------------------------------------
CREATE TABLE OPS_INCIDENT (
    INC_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    TITLE      VARCHAR(200)  NOT NULL,
    CONTENT    VARCHAR(8000),
    SEVERITY   VARCHAR(10)   NOT NULL,    -- 1~4 등급 (1:긴급)
    STATUS     VARCHAR(20)   NOT NULL,    -- RECEIVED/ANALYZING/ACTING/RESOLVED/CLOSED
    OCCR_DT    TIMESTAMP,                 -- 발생일시
    RCPT_DT    TIMESTAMP,                 -- 접수일시
    RESOLVE_DT TIMESTAMP,                 -- 조치완료일시
    CAUSE      VARCHAR(8000),             -- 장애원인
    ACTION     VARCHAR(8000),             -- 조치내용
    CHARGER_ID VARCHAR(20),               -- 처리담당자
    TARGET_RESOLVE_DT TIMESTAMP,          -- 목표복구일시(SLA)
    REF_PRB_ID BIGINT,                    -- 연계 문제 ID
    REG_ID     VARCHAR(20),
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_INCIDENT PRIMARY KEY (INC_ID)
);

-- 장애 처리이력 ---------------------------------------------------------
CREATE TABLE OPS_INCIDENT_HIS (
    HIS_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    INC_ID     BIGINT        NOT NULL,
    STATUS     VARCHAR(20)   NOT NULL,
    CONTENT    VARCHAR(8000),
    PROC_ID    VARCHAR(20),
    PROC_DT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_INCIDENT_HIS PRIMARY KEY (HIS_ID)
);

-- 변경관리 --------------------------------------------------------------
CREATE TABLE OPS_CHANGE (
    CHG_ID       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID       VARCHAR(20)  NOT NULL,
    TITLE        VARCHAR(200) NOT NULL,
    CHG_TYPE     VARCHAR(20)  NOT NULL,   -- PROGRAM/DATABASE/CONFIG/EMERGENCY
    PROC_TYPE    VARCHAR(20),             -- 처리유형(NORMAL/STANDARD/EMERGENCY : 일반/단순/긴급변경)
    REASON       VARCHAR(8000),           -- 변경사유
    CONTENT      VARCHAR(8000),           -- 변경내용
    STATUS       VARCHAR(20)  NOT NULL,   -- REQUESTED/REVIEWING/APPROVED/REJECTED/APPLIED/COMPLETED
    REQ_ID       VARCHAR(20),             -- 요청자
    REQ_DT       TIMESTAMP,               -- 요청일시
    APPR_ID      VARCHAR(20),             -- 승인자
    APPR_DT      TIMESTAMP,               -- 승인일시
    APPR_OPINION VARCHAR(4000),           -- 심의의견
    PLAN_DT      TIMESTAMP,               -- 적용 예정일시(from)
    APPLY_DT     TIMESTAMP,               -- 적용 예정일시(to)
    PROC_RESULT  VARCHAR(8000),           -- 처리 결과(변경 처리 완료 시 기록)
    LINKED_TYPE  VARCHAR(20),             -- 이관 연계 대상(RELEASE/INCIDENT)
    LINKED_ID    BIGINT,                  -- 이관 연계 대상 ID
    PIR_CONTENT  VARCHAR(8000),           -- 이행후검토(PIR) 내용
    PIR_DT       TIMESTAMP,               -- 이행후검토 일시
    REG_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CHANGE PRIMARY KEY (CHG_ID)
);

-- 배포(릴리즈)관리 ------------------------------------------------------
CREATE TABLE OPS_RELEASE (
    REL_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    CHG_ID     BIGINT,                    -- 연계 변경요청
    VER        VARCHAR(30)   NOT NULL,    -- 버전
    TITLE      VARCHAR(200)  NOT NULL,
    CONTENT    VARCHAR(8000),
    STATUS     VARCHAR(20)   NOT NULL,    -- PLANNED/APPROVED/DEPLOYING/DEPLOYED/ROLLBACK
    PLAN_DT    TIMESTAMP,                 -- 배포예정일시
    DEPLOY_DT  TIMESTAMP,                 -- 배포일시
    CHARGER_ID VARCHAR(20),
    RESULT     VARCHAR(4000),             -- 배포결과
    DEPLOY_REF    VARCHAR(100),           -- 배포한 git ref(태그/브랜치/커밋)
    DEPLOY_COMMIT VARCHAR(50),            -- 배포 커밋 해시
    DEPLOY_LOG    VARCHAR(4000),          -- 최근 배포 실행 로그
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_RELEASE PRIMARY KEY (REL_ID)
);

-- 운영점검(일일/정기) ---------------------------------------------------
CREATE TABLE OPS_CHECK (
    CHK_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    CHK_TYPE   VARCHAR(20)   NOT NULL,    -- DAILY/WEEKLY/MONTHLY
    CHK_DT     DATE          NOT NULL,    -- 점검일자
    CHKR_ID    VARCHAR(20),               -- 점검자
    RESULT     VARCHAR(20)   NOT NULL,    -- NORMAL/ABNORMAL
    REMARK     VARCHAR(4000),
    REG_DT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CHECK PRIMARY KEY (CHK_ID)
);

-- 운영점검 항목별 결과 --------------------------------------------------
CREATE TABLE OPS_CHECK_ITEM (
    ITEM_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CHK_ID      BIGINT       NOT NULL,
    ITEM_NM     VARCHAR(200) NOT NULL,    -- 점검항목명
    ITEM_RESULT VARCHAR(20)  NOT NULL,    -- NORMAL/ABNORMAL
    ITEM_REMARK VARCHAR(500),
    CONSTRAINT PK_OPS_CHECK_ITEM PRIMARY KEY (ITEM_ID)
);

-- =====================================================================
-- 표준운영절차 확장 모듈 (요청/테스트/연계/형상/운영상태/문제)
-- =====================================================================
DROP TABLE IF EXISTS OPS_DEPLOY_HIS;
DROP TABLE IF EXISTS OPS_INCIDENT_ESCAL;
DROP TABLE IF EXISTS OPS_CHANGE_CAB;
DROP TABLE IF EXISTS OPS_RELEASE_ITEM;
DROP TABLE IF EXISTS OPS_CSR_HIS;
DROP TABLE IF EXISTS OPS_CSR;
DROP TABLE IF EXISTS OPS_TEST_CASE;
DROP TABLE IF EXISTS OPS_TEST;
DROP TABLE IF EXISTS OPS_INTERFACE_HIS;
DROP TABLE IF EXISTS OPS_INTERFACE;
DROP TABLE IF EXISTS OPS_CI_HIS;
DROP TABLE IF EXISTS OPS_CI;
DROP TABLE IF EXISTS OPS_EVENT_HIS;
DROP TABLE IF EXISTS OPS_EVENT;
DROP TABLE IF EXISTS OPS_PROBLEM_INC;
DROP TABLE IF EXISTS OPS_KEDB;
DROP TABLE IF EXISTS OPS_PROBLEM_HIS;
DROP TABLE IF EXISTS OPS_PROBLEM;

-- ① 요청관리 (CSR) -----------------------------------------------------
CREATE TABLE OPS_CSR (
    CSR_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID      VARCHAR(20)   NOT NULL,
    TITLE       VARCHAR(200)  NOT NULL,
    CONTENT     VARCHAR(8000),
    CSR_TYPE    VARCHAR(20)   NOT NULL,   -- 요청 대분류 (CSR_TYPE 코드 : GENERAL/INCIDENT/CHANGE/BACKUP/CONFIG)
    CSR_SUB_TYPE VARCHAR(30),             -- 요청 소분류 (CSR_SUBTYPE 코드, UPPER_CODE=CSR_TYPE)
    PRIORITY    VARCHAR(20),              -- HIGH/MID/LOW
    STATUS      VARCHAR(20)   NOT NULL,   -- REQUESTED/RECEIVED/CLASSIFIED/IN_PROGRESS/PROCESSED/CLOSED/REJECTED
    REQ_ID      VARCHAR(20),              -- 요청자
    REQ_DT      TIMESTAMP,
    DUE_DT      DATE,                     -- 완료요구일
    CHARGER_ID  VARCHAR(20),              -- 처리담당자
    PROC_CONTENT VARCHAR(8000),           -- 처리내용
    PROC_DT     TIMESTAMP,
    LINKED_TYPE VARCHAR(20),              -- INCIDENT/CHANGE (이관 연계)
    LINKED_ID   BIGINT,
    SATISFACTION VARCHAR(10),             -- 만족도(1~5)
    REG_DT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CSR PRIMARY KEY (CSR_ID)
);
CREATE TABLE OPS_CSR_HIS (
    HIS_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CSR_ID   BIGINT       NOT NULL,
    STATUS   VARCHAR(20)  NOT NULL,
    CONTENT  VARCHAR(8000),
    PROC_ID  VARCHAR(20),
    PROC_DT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CSR_HIS PRIMARY KEY (HIS_ID)
);

-- 요청 소분류별 요청내용 템플릿 (CSR_SUBTYPE 코드 1:1) ------------------
DROP TABLE IF EXISTS OPS_CSR_TPL;
CREATE TABLE OPS_CSR_TPL (
    SUB_TYPE  VARCHAR(30)  NOT NULL,    -- CSR_SUBTYPE 코드
    CONTENT   VARCHAR(8000),            -- 요청내용 템플릿(리치텍스트)
    LEAD_DAYS INT,                      -- 완료요구일 자동설정용 소요 근무일(영업일)
    USE_AT    CHAR(1)      DEFAULT 'Y',
    REG_DT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CSR_TPL PRIMARY KEY (SUB_TYPE)
);

-- 요청 ↔ 대상 시스템 (다중 선택, N:M) ----------------------------------
-- OPS_CSR.SYS_ID 는 대표(첫번째) 시스템으로 유지하고 전체 선택은 본 테이블로 관리
DROP TABLE IF EXISTS OPS_CSR_SYS;
CREATE TABLE OPS_CSR_SYS (
    CSR_ID  BIGINT       NOT NULL,
    SYS_ID  VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_OPS_CSR_SYS PRIMARY KEY (CSR_ID, SYS_ID)
);

-- 요청 첨부파일 ---------------------------------------------------------
DROP TABLE IF EXISTS OPS_CSR_FILE;
CREATE TABLE OPS_CSR_FILE (
    FILE_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CSR_ID       BIGINT       NOT NULL,
    ORIGIN_NM    VARCHAR(260) NOT NULL,    -- 원본 파일명
    STORE_NM     VARCHAR(120) NOT NULL,    -- 저장 파일명(UUID)
    FILE_SIZE    BIGINT,
    CONTENT_TYPE VARCHAR(150),
    REG_ID       VARCHAR(20),
    REG_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CSR_FILE PRIMARY KEY (FILE_ID)
);

-- 메뉴 마스터 -----------------------------------------------------------
DROP TABLE IF EXISTS OPS_MENU_AUTH;
DROP TABLE IF EXISTS OPS_MENU;
CREATE TABLE OPS_MENU (
    MENU_ID    BIGINT       NOT NULL,
    MENU_NM    VARCHAR(100) NOT NULL,    -- 메뉴명
    MENU_URL   VARCHAR(200),             -- 링크(그룹은 NULL)
    MENU_KEY   VARCHAR(30),              -- 활성표시 키(컨트롤러 menu 속성과 매칭)
    MENU_TYPE  VARCHAR(10)  DEFAULT 'ITEM', -- GROUP(그룹헤더) / ITEM(메뉴)
    UPPER_ID   BIGINT,                   -- 상위 메뉴(그룹) ID
    SORT_ORDR  INT          DEFAULT 1,
    USE_AT     CHAR(1)      DEFAULT 'Y',
    CONSTRAINT PK_OPS_MENU PRIMARY KEY (MENU_ID)
);

-- 메뉴 권한(역할 ↔ 메뉴) -----------------------------------------------
CREATE TABLE OPS_MENU_AUTH (
    ROLE_ID  VARCHAR(20)  NOT NULL,      -- ADMIN/OPERATOR/USER
    MENU_ID  BIGINT       NOT NULL,
    CONSTRAINT PK_OPS_MENU_AUTH PRIMARY KEY (ROLE_ID, MENU_ID)
);

-- 역할(권한 그룹) 마스터
DROP TABLE IF EXISTS OPS_ROLE;
CREATE TABLE OPS_ROLE (
    ROLE_CD  VARCHAR(20)  NOT NULL,      -- 역할코드(권한). 사용자 ROLE/메뉴권한 ROLE_ID 와 매핑
    ROLE_NM  VARCHAR(50)  NOT NULL,      -- 역할명
    SORT_NO  INT          DEFAULT 99,    -- 정렬순서
    BUILTIN  CHAR(1)      DEFAULT 'N',   -- 내장역할(Y=삭제/코드변경 불가)
    USE_AT   CHAR(1)      DEFAULT 'Y',
    REG_DT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_ROLE PRIMARY KEY (ROLE_CD)
);

-- ④ 테스트관리 ---------------------------------------------------------
CREATE TABLE OPS_TEST (
    TEST_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    CHG_ID     BIGINT,                    -- 연계 변경
    TITLE      VARCHAR(200)  NOT NULL,
    TEST_TYPE  VARCHAR(20)   NOT NULL,    -- UNIT/INTEGRATION/PERFORMANCE/ACCEPTANCE
    TEST_ENV   VARCHAR(20)   NOT NULL,    -- DEV/OPS
    STATUS     VARCHAR(20)   NOT NULL,    -- PLANNED/TESTING/ANALYZED/CLOSED/FAILED
    PLAN_DT    DATE,
    TESTER_ID  VARCHAR(20),
    RESULT_SUMMARY VARCHAR(8000),
    REG_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_TEST PRIMARY KEY (TEST_ID)
);
CREATE TABLE OPS_TEST_CASE (
    CASE_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    TEST_ID    BIGINT       NOT NULL,
    CASE_NM    VARCHAR(200) NOT NULL,     -- 테스트 케이스명
    EXPECTED   VARCHAR(500),              -- 기대결과
    CASE_RESULT VARCHAR(20) NOT NULL,     -- PASS/FAIL/NA
    REMARK     VARCHAR(500),
    CONSTRAINT PK_OPS_TEST_CASE PRIMARY KEY (CASE_ID)
);

-- ⑤ 연계관리 ----------------------------------------------------------
CREATE TABLE OPS_INTERFACE (
    INTF_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    TITLE      VARCHAR(200)  NOT NULL,
    PARTNER_SYS VARCHAR(100),             -- 연계 상대 시스템
    IF_TYPE    VARCHAR(20)   NOT NULL,    -- SYNC/ASYNC/BATCH/API
    DATA_DESC  VARCHAR(8000),             -- 연계 데이터/내용
    STATUS     VARCHAR(20)   NOT NULL,    -- REQUESTED/REVIEWING/PLANNING/WORKING/TESTING/COMPLETED/REJECTED
    REQ_ID     VARCHAR(20),
    REQ_DT     TIMESTAMP,
    CHARGER_ID VARCHAR(20),
    PLAN_DT    DATE,
    COMPLETE_DT TIMESTAMP,
    RESULT     VARCHAR(4000),
    REG_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_INTERFACE PRIMARY KEY (INTF_ID)
);
CREATE TABLE OPS_INTERFACE_HIS (
    HIS_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    INTF_ID  BIGINT       NOT NULL,
    STATUS   VARCHAR(20)  NOT NULL,
    CONTENT  VARCHAR(8000),
    PROC_ID  VARCHAR(20),
    PROC_DT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_INTERFACE_HIS PRIMARY KEY (HIS_ID)
);

-- ⑥ 형상관리 (형상항목 CI + 통제/감사 이력) ---------------------------
CREATE TABLE OPS_CI (
    CI_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    CI_NM      VARCHAR(200)  NOT NULL,    -- 형상항목명
    CI_TYPE    VARCHAR(20)   NOT NULL,    -- SOURCE/LIBRARY/DOCUMENT/CONFIG/DB
    VER        VARCHAR(30),               -- 버전(베이스라인)
    CI_STATUS  VARCHAR(20)   NOT NULL,    -- IDENTIFIED/BASELINED/CHECKED_OUT/CHECKED_IN
    LOCATION   VARCHAR(300),              -- 저장위치(저장소/경로)
    OWNER_ID   VARCHAR(20),               -- 형상담당자
    CI_DESC    VARCHAR(4000),
    REG_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CI PRIMARY KEY (CI_ID)
);
CREATE TABLE OPS_CI_HIS (
    HIS_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CI_ID    BIGINT       NOT NULL,
    CHG_TYPE VARCHAR(20)  NOT NULL,       -- IDENTIFY/CHECKOUT/CHECKIN/BASELINE/AUDIT
    VER      VARCHAR(30),
    CONTENT  VARCHAR(8000),
    PROC_ID  VARCHAR(20),
    PROC_DT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CI_HIS PRIMARY KEY (HIS_ID)
);

-- ⑦ 운영상태관리 (모니터링 이벤트) ------------------------------------
CREATE TABLE OPS_EVENT (
    EVT_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    TITLE      VARCHAR(200)  NOT NULL,
    EVT_TYPE   VARCHAR(20)   NOT NULL,    -- CPU/MEMORY/DISK/PROCESS/NETWORK/APP
    SEVERITY   VARCHAR(20)   NOT NULL,    -- INFO/WARN/CRITICAL
    STATUS     VARCHAR(20)   NOT NULL,    -- DETECTED/ANALYZING/ACTING/HANDLED/ESCALATED/CLOSED
    OCCR_DT    TIMESTAMP,
    CONTENT    VARCHAR(8000),
    ACTION     VARCHAR(8000),
    CHARGER_ID VARCHAR(20),
    LINKED_INC_ID BIGINT,                 -- 장애 에스컬레이션 연계
    REG_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_EVENT PRIMARY KEY (EVT_ID)
);
CREATE TABLE OPS_EVENT_HIS (
    HIS_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    EVT_ID   BIGINT       NOT NULL,
    STATUS   VARCHAR(20)  NOT NULL,
    CONTENT  VARCHAR(8000),
    PROC_ID  VARCHAR(20),
    PROC_DT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_EVENT_HIS PRIMARY KEY (HIS_ID)
);

-- ⑨ 문제관리 (문제 + 이력 + 장애연계 + 알려진오류 KEDB) ---------------
CREATE TABLE OPS_PROBLEM (
    PRB_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    SYS_ID     VARCHAR(20)   NOT NULL,
    TITLE      VARCHAR(200)  NOT NULL,
    CONTENT    VARCHAR(8000),
    PRIORITY   VARCHAR(20),               -- HIGH/MID/LOW
    STATUS     VARCHAR(20)   NOT NULL,    -- REGISTERED/ANALYZING/IDENTIFIED/RESOLVING/RESOLVED/CLOSED
    ROOT_CAUSE VARCHAR(8000),             -- 근본원인
    SOLUTION   VARCHAR(8000),             -- 해결책(항구대책)
    REG_ID     VARCHAR(20),
    REG_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CHARGER_ID VARCHAR(20),
    RESOLVE_DT TIMESTAMP,
    CONSTRAINT PK_OPS_PROBLEM PRIMARY KEY (PRB_ID)
);
CREATE TABLE OPS_PROBLEM_HIS (
    HIS_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRB_ID   BIGINT       NOT NULL,
    STATUS   VARCHAR(20)  NOT NULL,
    CONTENT  VARCHAR(8000),
    PROC_ID  VARCHAR(20),
    PROC_DT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_PROBLEM_HIS PRIMARY KEY (HIS_ID)
);
CREATE TABLE OPS_PROBLEM_INC (
    PRB_ID   BIGINT       NOT NULL,       -- 문제
    INC_ID   BIGINT       NOT NULL,       -- 연계 장애
    CONSTRAINT PK_OPS_PROBLEM_INC PRIMARY KEY (PRB_ID, INC_ID)
);
CREATE TABLE OPS_KEDB (
    KEDB_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRB_ID     BIGINT,                    -- 출처 문제
    TITLE      VARCHAR(200)  NOT NULL,
    SYMPTOM    VARCHAR(8000),             -- 증상
    CAUSE      VARCHAR(8000),             -- 원인
    WORKAROUND VARCHAR(8000),             -- 임시조치
    SOLUTION   VARCHAR(8000),             -- 해결책
    REG_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_KEDB PRIMARY KEY (KEDB_ID)
);

-- =====================================================================
-- 현행 모듈 보강 (장애 SLA/에스컬레이션, 변경 CAB, 배포 항목)
-- =====================================================================
-- 장애 에스컬레이션 이력
CREATE TABLE OPS_INCIDENT_ESCAL (
    ESCAL_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    INC_ID      BIGINT       NOT NULL,
    ESCAL_LEVEL VARCHAR(20)  NOT NULL,    -- L1/L2/MANAGER/VENDOR
    ESCAL_TO    VARCHAR(100),             -- 에스컬레이션 대상(담당/조직)
    REASON      VARCHAR(4000),
    ESCAL_BY    VARCHAR(20),
    ESCAL_DT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_INCIDENT_ESCAL PRIMARY KEY (ESCAL_ID)
);
-- 변경 CAB(변경자문위원회) 심의 이력
CREATE TABLE OPS_CHANGE_CAB (
    CAB_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CHG_ID    BIGINT       NOT NULL,
    DECISION  VARCHAR(20)  NOT NULL,      -- APPROVED/REJECTED/HOLD
    OPINION   VARCHAR(4000),
    REVIEWER  VARCHAR(500),               -- 심의위원(다중: 콤마구분 사용자ID)
    CAB_DT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_CHANGE_CAB PRIMARY KEY (CAB_ID)
);
-- 배포 항목
CREATE TABLE OPS_RELEASE_ITEM (
    RITEM_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    REL_ID      BIGINT       NOT NULL,
    ITEM_NM     VARCHAR(200) NOT NULL,    -- 배포 항목명(모듈/파일 등)
    ITEM_DESC   VARCHAR(500),
    ITEM_RESULT VARCHAR(20),              -- SUCCESS/FAIL/SKIP
    CONSTRAINT PK_OPS_RELEASE_ITEM PRIMARY KEY (RITEM_ID)
);
-- Git 자동배포 실행 이력
CREATE TABLE OPS_DEPLOY_HIS (
    DEPLOY_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    REL_ID      BIGINT       NOT NULL,
    DEPLOY_REF  VARCHAR(100),             -- 배포 ref(태그/브랜치/커밋)
    COMMIT_HASH VARCHAR(50),
    RESULT      VARCHAR(20)  NOT NULL,    -- SUCCESS/FAIL
    DEPLOY_TYPE VARCHAR(20),              -- DEPLOY/ROLLBACK
    LOG         VARCHAR(4000),
    EXEC_BY     VARCHAR(20),
    EXEC_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_DEPLOY_HIS PRIMARY KEY (DEPLOY_ID)
);

-- =====================================================================
-- 결재선(검토/승인/처리자 라인) / 공유  ※ 업무 공통(bizType+bizId 로 느슨 연결)
-- =====================================================================
DROP TABLE IF EXISTS OPS_APPR_LINE;
CREATE TABLE OPS_APPR_LINE (
    APPR_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    BIZ_TYPE    VARCHAR(20)  NOT NULL,           -- CHANGE/RELEASE/CSR/INCIDENT/PROBLEM/TEST/INTERFACE/CI/EVENT
    BIZ_ID      BIGINT       NOT NULL,           -- 업무 레코드 ID
    LINE_TYPE   VARCHAR(10)  NOT NULL,           -- REVIEW(검토)/APPROVE(승인)/HANDLE(처리)
    STEP_NO     INT          DEFAULT 1,          -- 단계(동일 단계 = 병렬)
    SORT_NO     INT          DEFAULT 1,          -- 단계 내 표시순서
    ASSIGNEE_ID VARCHAR(20)  NOT NULL,           -- 지정 대상자
    TARGET_TYPE VARCHAR(20),                      -- 지정 근거(USER/DEPT/REQUESTER/ALL) — 부서/전체 전개분은 열람 제외
    STATUS      VARCHAR(10)  DEFAULT 'PENDING',  -- PENDING/APPROVED/REJECTED/REVIEWED/DONE
    OPINION     VARCHAR(4000),                   -- 의견
    ACT_DT      TIMESTAMP,                       -- 처리일시
    REG_ID      VARCHAR(20),
    REG_DT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_APPR_LINE PRIMARY KEY (APPR_ID)
);

DROP TABLE IF EXISTS OPS_SHARE;
CREATE TABLE OPS_SHARE (
    SHARE_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    BIZ_TYPE    VARCHAR(20)  NOT NULL,
    BIZ_ID      BIGINT       NOT NULL,
    USER_ID     VARCHAR(20)  NOT NULL,           -- 공유 대상자
    SHARE_MEMO  VARCHAR(500),                    -- 공유 메모
    READ_AT     CHAR(1)      DEFAULT 'N',         -- 열람여부
    SHARED_BY   VARCHAR(20),                     -- 공유한 사람
    SHARED_DT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_SHARE PRIMARY KEY (SHARE_ID)
);

-- =====================================================================
-- 결재선/공유 기본 템플릿 (관리별 공통 기본설정)
-- =====================================================================
DROP TABLE IF EXISTS OPS_APPR_TEMPLATE;
CREATE TABLE OPS_APPR_TEMPLATE (
    TPL_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    BIZ_TYPE    VARCHAR(20)  NOT NULL,           -- CHANGE/RELEASE/CSR/...
    SYS_ID      VARCHAR(20),                     -- 대상 시스템(null=전체)
    CLASS_CD    VARCHAR(30),                     -- 요청 분류(업무유형코드, null=전체)
    KIND        VARCHAR(10)  NOT NULL,           -- LINE(결재선) / SHARE(공유)
    LINE_TYPE   VARCHAR(10),                     -- REVIEW/APPROVE/HANDLE (KIND=LINE)
    STEP_NO     INT          DEFAULT 1,
    SORT_NO     INT          DEFAULT 1,
    TARGET_TYPE VARCHAR(10)  NOT NULL,           -- USER/DEPT/REQUESTER/ALL
    TARGET_VALUE VARCHAR(50),                    -- userId(USER) / deptNm(DEPT) / null
    MEMO        VARCHAR(500),                    -- 공유 메모(KIND=SHARE)
    REG_DT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_APPR_TEMPLATE PRIMARY KEY (TPL_ID)
);

-- =====================================================================
-- 부서 마스터 (기준정보)
-- =====================================================================
DROP TABLE IF EXISTS OPS_DEPT;
CREATE TABLE OPS_DEPT (
    DEPT_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    DEPT_CD    VARCHAR(20),                     -- 부서코드
    DEPT_NM    VARCHAR(100) NOT NULL,           -- 부서명
    UPPER_ID   BIGINT,                          -- 상위부서
    MNGR_ID    VARCHAR(20),                     -- 부서장(사용자ID)
    SORT_ORDR  INT          DEFAULT 1,
    DEPT_DESC  VARCHAR(500),
    USE_AT     CHAR(1)      DEFAULT 'Y',
    REG_DT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OPS_DEPT PRIMARY KEY (DEPT_ID),
    CONSTRAINT UQ_OPS_DEPT_CD UNIQUE (DEPT_CD)
);
