# =====================================================================
# 전역 프로퍼티 (전자정부 표준프레임워크 globals)
# =====================================================================
# Git 자동배포
ops.deploy.workspace=${java.io.tmpdir}/egov-sop/deploy
ops.deploy.script-timeout-sec=60
